version: '3.8'

services:
  pmm-server:
    image: percona/pmm-server:${PMM_TAG}
    container_name: pmm-server
    restart: always
    ports:
      - "${PMM_PORT}:8443"
    environment:
      - PMM_WATCHTOWER_HOST=http://watchtower:8080
      - PMM_WATCHTOWER_TOKEN=${WATCHTOWER_TOKEN}
    networks:
      - pmm-net

  watchtower:
    image: percona/watchtower
    container_name: watchtower
    restart: always
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_TOKEN}
      - WATCHTOWER_HTTP_LISTEN_PORT=8080
      - WATCHTOWER_HTTP_API_UPDATE=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pmm-net

networks:
  pmm-net:
    driver: bridge
